/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AuditRequest = IDL.Record({
  'name' : IDL.Text,
  'instagramHandle' : IDL.Text,
  'email' : IDL.Text,
  'submissionTime' : Time,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'submissionTime' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllAuditRequestsSortedNewestFirst' : IDL.Func(
      [],
      [IDL.Vec(AuditRequest)],
      ['query'],
    ),
  'getAllContactMessagesSortedNewestFirst' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAuditRequestCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getContactSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'hasAuditRequests' : IDL.Func([], [IDL.Bool], ['query']),
  'hasContactSubmissions' : IDL.Func([], [IDL.Bool], ['query']),
  'submitAuditRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AuditRequest = IDL.Record({
    'name' : IDL.Text,
    'instagramHandle' : IDL.Text,
    'email' : IDL.Text,
    'submissionTime' : Time,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'submissionTime' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllAuditRequestsSortedNewestFirst' : IDL.Func(
        [],
        [IDL.Vec(AuditRequest)],
        ['query'],
      ),
    'getAllContactMessagesSortedNewestFirst' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAuditRequestCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getContactSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'hasAuditRequests' : IDL.Func([], [IDL.Bool], ['query']),
    'hasContactSubmissions' : IDL.Func([], [IDL.Bool], ['query']),
    'submitAuditRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };